export const text = {
  COGNITO_POST_PASSED: '✓ source_cognito_post: PASSED',
  COGNITO_POST_FAILED: '✕ source_cognito_post: FAILED',
  COGNITO_POST_NOTE: 'Note: Check email and take note of confirmation code.',
  COGNITO_CONFIRM_PASSED: '✓ source_cognito_confirm_put: PASSED',
  COGNITO_CONFIRM_FAILED: '✕ source_cognito_confirm_put: FAILED',
  COGNITO_PUT_PASSED: '✓ source_cognito_put: PASSED',
  COGNITO_PUT_FAILED: '✕ source_cognito_put: FAILED',
  COGNITO_GET_PASSED: '✓ source_cognito_get: PASSED',
  COGNITO_GET_FAILED: '✕ source_cognito_get: FAILED',
  COGNITO_TOKEN_GET_PASSED: '✓ source_cognito_token_get: PASSED',
  COGNITO_TOKEN_GET_FAILED: '✕ source_cognito_token_get: FAILED',
  COGNITO_MFA_POST_PASSED: '✓ source_cognito_mfa_post: PASSED',
  COGNITO_MFA_POST_FAILED: '✕ source_cognito_mfa_post: FAILED',
  COGNITO_VERIFY_USER_PUT_PASSED: '✓ source_cognito_verify_user_attribute_put: PASSED',
  COGNITO_VERIFY_USER_PUT_FAILED: '✕ source_cognito_verify_user_attribute_put: FAILED',
  COGNITO_VERIFY_USER_NOTE: 'Note: Confirmation code has been sent to the new email.',
  COGNITO_RESEND_CODE_GET_PASSED: '✓ source_cognito_resend_confirmation_code_get: PASSED',
  COGNITO_RESEND_CODE_GET_FAILED: '✕ source_cognito_resend_confirmation_code_get: FAILED',
  COGNITO_RESEND_CODE_GET_NOTE: 'Note: Confirmation code has been re-sent to the new email.',
  COGNITO_FORGOT_PW_PASSED: '✓ source_cognito_forgot_password_post: PASSED',
  COGNITO_FORGOT_PW_FAILED: '✕ source_cognito_forgot_password_post: FAILED',
  COGNITO_CONFIRM_FORGOT_PW_PASSED: '✓ source_cognito_confirm_forgot_password_put: PASSED',
  COGNITO_CONFIRM_FORGOT_PW_FAILED: '✕ source_cognito_confirm_forgot_password_put: FAILED',
  COGNITO_FORGOT_PW_NOTE: 'Note: Confirmation code has been sent to email.',
  USER_POST_PASSED: '✓ source_user_post: PASSED',
  USER_POST_FAILED: '✕ source_user_post: FAILED',
  USER_DELETE_PASSED: '✓ source_user_delete: PASSED',
  USER_DELETE_FAILED: '✕ source_user_delete: FAILED',
  USER_DELETE_NOTE: 'Note: You are about to test the API used in account deletion.',
  USER_DELETE_COMPLETE_NOTE: 'Note: You have successfully deleted the account.',
  USER_PUT_PASSED: '✓ source_user_put: PASSED',
  USER_PUT_FAILED: '✕ source_user_put: FAILED',
  USER_NOTIF_POST_PASSED: '✓ source_user_notification_post: PASSED',
  USER_NOTIF_POST_FAILED: '✕ source_user_notification_post: FAILED',
  USER_NOTIF_PUT_PASSED: '✓ source_user_notification_put: PASSED',
  USER_NOTIF_PUT_FAILED: '✕ source_user_notification_put: FAILED',
  USER_NOTIF_GET_PASSED: '✓ source_user_notification_get: PASSED',
  USER_NOTIF_GET_FAILED: '✕ source_user_notification_get: FAILED',
  USER_GET_PASSED: '✓ source_user_get: PASSED',
  USER_GET_FAILED: '✕ source_user_get: FAILED',
  MASTER_CODE_GET_PASSED: '✓ master_code_get: PASSED',
  MASTER_CODE_GET_FAILED: '✕ master_code_get: FAILED',
  CHANGE_MAIL_PRETEST_NOTE: 'Note: You are about to test the APIs used in change email setting.',
  CHANGE_MAIL_COMPLETE_NOTE: 'Note: Done testing the APIs in change email setting.',
  FORGOT_PW_PRETEST_NOTE: 'Note: You are about to test the APIs used in forgot password.',
  FORGOT_PW_COMPLETE_NOTE: 'Note: Done testing the APIs in forgot password.',
  LOGIN_POST_PASSED: '✓ source_login_post: PASSED',
  LOGIN_POST_FAILED: '✕ source_login_post: FAILED',
  LOGIN_SUCCESS_NOTE: 'Note: Login process is finished and successful.',
  LOGIN_PRETEST_NOTE: 'Note: You are about to test the APIs used in login process.',
  LOGIN_COMPLETE_NOTE: 'Note: Done testing the APIs in login process.',
  NOTIFICATION_PRETEST_NOTE_1: 'Note: You are about to test the APIs used in notification setting.',
  NOTIFICATION_PRETEST_NOTE_2: 'Note: The API responsible for creating a notif data can only be run once.',
  NOTIFICATION_PRETEST_NOTE_3: 'Note: In order to test this set of APIs, the account should be deleted then registered again.',
  NOTIFICATION_COMPLETE_NOTE: 'Note: Done testing the APIs in notification setting.',
  REGISTRATION_COMPLETE_NOTE: 'Note: You have finished the registration process.',
  REGISTRATION_PRETEST_NOTE: 'Note: You are about to test the APIs used in registration process.',
  SETTING_PRETEST_NOTE_1: 'Note: You are about to test the APIs used in setting page.',
  SETTING_PRETEST_NOTE_2: 'Note: Excluded in this test are APIS used in change email, notification and account deletion',
  SETTING_PRETEST_NOTE_3: 'Note: Each of the stated features has its own test file.',
  SETTING_COMPLETE_NOTE: 'Note: Done testing the APIs in setting page.',
  WARNING_NOTE: 'Warning: Execute this with precaution.',
  ASTERISK_NOTE: '**********************************************************************'
};

export const headers = {
  'Content-Type': 'application/json'
}