export const text = {
  COGNITO_POST_PASSED: '✓ source_cognito_post: PASSED',
  COGNITO_POST_FAILED: '✕ source_cognito_post: FAILED',
  COGNITO_POST_NOTE: 'Note: Check email and take note of confirmation code.',
  COGNITO_CONFIRM_PASSED: '✓ source_cognito_confirm_put: PASSED',
  COGNITO_CONFIRM_FAILED: '✕ source_cognito_confirm_put: FAILED',
  COGNITO_PUT_PASSED: '✓ source_cognito_put: PASSED',
  COGNITO_PUT_FAILED: '✕ source_cognito_put: FAILED',
  COGNITO_GET_PASSED: '✓ source_cognito_get: PASSED',
  COGNITO_GET_FAILED: '✕ source_cognito_get: FAILED',
  COGNITO_TOKEN_GET_PASSED: '✓ source_cognito_token_get: PASSED',
  COGNITO_TOKEN_GET_FAILED: '✕ source_cognito_token_get: FAILED',
  COGNITO_MFA_POST_PASSED: '✓ source_cognito_mfa_post: PASSED',
  COGNITO_MFA_POST_FAILED: '✕ source_cognito_mfa_post: FAILED',
  COGNITO_AUTH_CHALLENGE_PASSED: '✓ source_cognito_auth_challenge: PASSED',
  COGNITO_AUTH_CHALLENGE_FAILED: '✕ source_cognito_auth_challenge: FAILED',
  COGNITO_VERIFY_USER_PUT_PASSED: '✓ source_cognito_verify_user_attribute_put: PASSED',
  COGNITO_VERIFY_USER_PUT_FAILED: '✕ source_cognito_verify_user_attribute_put: FAILED',
  COGNITO_VERIFY_USER_GET_PASSED: '✓ source_cognito_verify_user_attribute_get: PASSED',
  COGNITO_VERIFY_USER_GET_FAILED: '✕ source_cognito_verify_user_attribute_get: FAILED',
  COGNITO_VERIFY_USER_NOTE: 'Note: Confirmation code has been sent to the new email.',
  COGNITO_RESEND_CODE_GET_PASSED: '✓ source_cognito_resend_confirmation_code_get: PASSED',
  COGNITO_RESEND_CODE_GET_FAILED: '✕ source_cognito_resend_confirmation_code_get: FAILED',
  COGNITO_RESEND_CODE_GET_NOTE: 'Note: Confirmation code has been re-sent to the new email.',
  COGNITO_FORGOT_PW_PASSED: '✓ source_cognito_forgot_password_post: PASSED',
  COGNITO_FORGOT_PW_FAILED: '✕ source_cognito_forgot_password_post: FAILED',
  COGNITO_CONFIRM_FORGOT_PW_PASSED: '✓ source_cognito_confirm_forgot_password_put: PASSED',
  COGNITO_CONFIRM_FORGOT_PW_FAILED: '✕ source_cognito_confirm_forgot_password_put: FAILED',
  COGNITO_UPDATE_DATE_GET_PASSED: '✓ source_cognito_update_date_get: PASSED',
  COGNITO_UPDATE_DATE_GET_FAILED: '✕ source_cognito_update_date_get: FAILED',
  COGNITO_FORGOT_PW_NOTE: 'Note: Confirmation code has been sent to email.',
  MAIL_INQUIRY_PASSED: '✓ source_mail_inquiry: PASSED',
  MAIL_INQUIRY_FAILED: '✕ source_mail_inquiry: FAILED',
  RSS_ARTICLE_GET_PASSED: '✓ source_rss_article_get: PASSED',
  RSS_ARTICLE_GET_FAILED: '✕ source_rss_article_get: FAILED',
  SNS_CCODE_GET_PASSED: '✓ source_sns_ccode_get: PASSED',
  SNS_CCODE_GET_FAILED: '✕ source_sns_ccode_get: FAILED',
  USER_POST_PASSED: '✓ source_user_post: PASSED',
  USER_POST_FAILED: '✕ source_user_post: FAILED',
  USER_DELETE_PASSED: '✓ source_user_delete: PASSED',
  USER_DELETE_FAILED: '✕ source_user_delete: FAILED',
  USER_DELETE_NOTE: 'Note: You are about to test the API used in account deletion.',
  USER_DELETE_COMPLETE_NOTE: 'Note: You have successfully deleted the account.',
  USER_PUT_PASSED: '✓ source_user_put: PASSED',
  USER_PUT_FAILED: '✕ source_user_put: FAILED',
  USER_NOTIF_POST_PASSED: '✓ source_user_notification_post: PASSED',
  USER_NOTIF_POST_FAILED: '✕ source_user_notification_post: FAILED',
  USER_NOTIF_PUT_PASSED: '✓ source_user_notification_put: PASSED',
  USER_NOTIF_PUT_FAILED: '✕ source_user_notification_put: FAILED',
  USER_NOTIF_GET_PASSED: '✓ source_user_notification_get: PASSED',
  USER_NOTIF_GET_FAILED: '✕ source_user_notification_get: FAILED',
  USER_GET_PASSED: '✓ source_user_get: PASSED',
  USER_GET_FAILED: '✕ source_user_get: FAILED',
  USER_SERVICE_POST_PASSED: '✓ source_user_service_post: PASSED',
  USER_SERVICE_POST_FAILED: '✕ source_user_service_post: FAILED',
  USER_SERVICE_PUT_PASSED: '✓ source_user_service_put: PASSED',
  USER_SERVICE_PUT_FAILED: '✕ source_user_service_put: FAILED',
  USER_SERVICE_GET_PASSED: '✓ source_user_service_get: PASSED',
  USER_SERVICE_GET_FAILED: '✕ source_user_service_get: FAILED',
  MASTER_CODE_GET_PASSED: '✓ master_code_get: PASSED',
  MASTER_CODE_GET_FAILED: '✕ master_code_get: FAILED',
  CHANGE_MAIL_PRETEST_NOTE: 'Note: You are about to test the APIs used in change email setting.',
  CHANGE_MAIL_COMPLETE_NOTE: 'Note: Done testing the APIs in change email setting.',
  FORGOT_PW_PRETEST_NOTE: 'Note: You are about to test the APIs used in forgot password.',
  FORGOT_PW_COMPLETE_NOTE: 'Note: Done testing the APIs in forgot password.',
  LOGIN_POST_PASSED: '✓ source_login_post: PASSED',
  LOGIN_POST_FAILED: '✕ source_login_post: FAILED',
  LOGIN_HISTORY_POST_PASSED: '✓ source_user_login_history_post: PASSED',
  LOGIN_HISTORY_POST_FAILED: '✕ source_user_login_history_post: FAILED',
  LOGIN_HISTORY_GET_PASSED: '✓ source_user_login_history_get: PASSED',
  LOGIN_HISTORY_GET_FAILED: '✕ source_user_login_history_get: FAILED',
  LOGIN_HISTORY_CHECK_PASSED: '✓ source_user_login_history_check: PASSED',
  LOGIN_HISTORY_CHECK_FAILED: '✕ source_user_login_history_check: FAILED',
  LOGIN_SUCCESS_NOTE: 'Note: Login process is finished and successful.',
  LOGIN_PRETEST_NOTE: 'Note: You are about to test the APIs used in login process.',
  LOGIN_COMPLETE_NOTE: 'Note: Done testing the APIs in login process.',
  NOTIFICATION_PRETEST_NOTE_1: 'Note: You are about to test the APIs used in notification setting.',
  NOTIFICATION_PRETEST_NOTE_2: 'Note: The API responsible for creating a notif data can only be run once.',
  NOTIFICATION_PRETEST_NOTE_3: 'Note: In order to test this set of APIs, the account should be deleted then registered again.',
  NOTIFICATION_COMPLETE_NOTE: 'Note: Done testing the APIs in notification setting.',
  OTHERS_PRETEST_NOTE: 'Note: You are about to test the rest of the APIs (login history, mail inquiry, etc.).',
  OTHERS_COMPLETE_NOTE: 'Note: Done testing the other APIs.',
  REGISTRATION_COMPLETE_NOTE: 'Note: You have finished the registration process.',
  REGISTRATION_PRETEST_NOTE: 'Note: You are about to test the APIs used in registration process.',
  SETTING_PRETEST_NOTE_1: 'Note: You are about to test the APIs used in setting page.',
  SETTING_PRETEST_NOTE_2: 'Note: Excluded in this test are APIS used in change email, notification and account deletion',
  SETTING_PRETEST_NOTE_3: 'Note: Each of the stated features has its own test file.',
  SETTING_COMPLETE_NOTE: 'Note: Done testing the APIs in setting page.',
  TWO_WAY_AUTH_NOTE_1: 'Note: You are about to test the APIs used in 2-way authentication.',
  TWO_WAY_AUTH_NOTE_2: 'Note: Before executing this set of tests make sure to enable the 2-way auth in browser.',
  TWO_WAY_COMPLETE_NOTE: 'Note: Done testing the APIs in 2-way auth. The 2-way auth has also been disabled.',
  USER_SERVICE_PRETEST_NOTE_1: 'Note: You are about to test the APIs used in user service.',
  USER_SERVICE_PRETEST_NOTE_2: 'Note: The API responsible for creating a user service data can only be run once.',
  USER_SERVICE_PRETEST_NOTE_3: 'Note: In order to test this set of APIs, the account should be deleted then registered again.',
  USER_SERVICE_COMPLETE_NOTE: 'Note: Done testing the APIs used in user service.',
  WARNING_NOTE: 'Warning: Execute this with precaution.',
  ASTERISK_NOTE: '**********************************************************************'
};

export const headers = {
  'Content-Type': 'application/json'
}